# Generated by Django 3.2.11 on 2022-07-14 09:13

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("leaf", "Leaf"),
                            ("arrow", "Arrow"),
                            ("animation", "Animation"),
                        ],
                        default="",
                        max_length=255,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "cta_text",
                    models.TextField(blank=True, default="", verbose_name="CTA text"),
                ),
                (
                    "cta_url",
                    models.URLField(blank=True, default="", verbose_name="CTA URL"),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "headline",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "sub_heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Sub heading",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "intro",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Intro",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")],
                                                label="Icon",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "dark_background",
                                            wagtail.core.blocks.BooleanBlock(
                                                default=False,
                                                label="Dark background",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "teaser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "blog_chooser",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Blog chooser",
                                                page_type=[],
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "page_chooser",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Page chooser",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "url_chooser",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="URL chooser",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "standalonecta",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.TextBlock(
                                                default="", label="Text", required=True
                                            ),
                                        ),
                                        (
                                            "short_description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Short description",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "highlight",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=True
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                max_length=100,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Subheading",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")],
                                                label="Icon",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image_on_right",
                                            wagtail.core.blocks.BooleanBlock(
                                                default=False,
                                                label="Image on right",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "iconbullets",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")], label="Icon"
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "quotes",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "quote_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Quote text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author_name",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Author name",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "author_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Author image", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "getstartedchooser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "choose",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                label="Choose",
                                                required=False,
                                                target_model="snippets.GetStarted",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        default="",
                        verbose_name="Body",
                    ),
                ),
                (
                    "heading",
                    models.TextField(
                        default="", max_length=100, verbose_name="Heading"
                    ),
                ),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True, default="", verbose_name="Sub heading"
                    ),
                ),
                (
                    "intro",
                    wagtail.core.fields.RichTextField(
                        blank=True, default="", verbose_name="Intro"
                    ),
                ),
                (
                    "cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="CTA page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.TextField(default="", verbose_name="Heading")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[("leaf", "Leaf")],
                        default="",
                        max_length=255,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "cta_text",
                    models.TextField(blank=True, default="", verbose_name="CTA text"),
                ),
                (
                    "cta_url",
                    models.URLField(blank=True, default="", verbose_name="CTA URL"),
                ),
                (
                    "intro",
                    wagtail.core.fields.RichTextField(
                        blank=True, default="", verbose_name="Intro"
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "headline",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "sub_heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Sub heading",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "intro",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Intro",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")],
                                                label="Icon",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "dark_background",
                                            wagtail.core.blocks.BooleanBlock(
                                                default=False,
                                                label="Dark background",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "teaser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "blog_chooser",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Blog chooser",
                                                page_type=[],
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "page_chooser",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Page chooser",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "url_chooser",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="URL chooser",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "standalonecta",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.TextBlock(
                                                default="", label="Text", required=True
                                            ),
                                        ),
                                        (
                                            "short_description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Short description",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "highlight",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=True
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                max_length=100,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Subheading",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")],
                                                label="Icon",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image_on_right",
                                            wagtail.core.blocks.BooleanBlock(
                                                default=False,
                                                label="Image on right",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "iconbullets",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")], label="Icon"
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "quotes",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "quote_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Quote text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author_name",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Author name",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "author_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Author image", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "getstartedchooser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "choose",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                label="Choose",
                                                required=False,
                                                target_model="snippets.GetStarted",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "quote",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.core.blocks.TextBlock(
                                                default="", label="Quote", required=True
                                            ),
                                        ),
                                        (
                                            "author",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Author",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Author image", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "rich_text",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "h2",
                                                    "h3",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document",
                                                ],
                                                label="Rich text",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "textandmedia",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "embed",
                                            wagtail.embeds.blocks.EmbedBlock(
                                                default="",
                                                label="Embed",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="CTA text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image_on_right",
                                            wagtail.core.blocks.BooleanBlock(
                                                default=False,
                                                label="Image on right",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "signupform",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "signup_form",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                label="Signup form",
                                                required=True,
                                                target_model="snippets.SignupForm",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            ("comparisontable", wagtail.core.blocks.StructBlock([])),
                            (
                                "cards",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "cta_url",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="CTA URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Subheading",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")], label="Icon"
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="",
                                                features=["bold", "italic"],
                                                label="Description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="CTA text",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        default="",
                        verbose_name="Body",
                    ),
                ),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True, default="", verbose_name="Sub heading"
                    ),
                ),
                (
                    "cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="CTA page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
