# Generated by Django 3.2.11 on 2022-07-14 09:13

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GetStarted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Heading",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "icon",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[("leaf", "Leaf")], label="Icon"
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "subheading",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "subheading",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Subheading",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "description",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Description",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "pagechooser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "page_chooser",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Page chooser",
                                                page_type=[],
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "externallink",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "external_link",
                                            wagtail.core.blocks.URLBlock(
                                                default="",
                                                label="External link",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        default="",
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Get started",
            },
        ),
        migrations.CreateModel(
            name="SignupForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.TextField(default="", verbose_name="Heading")),
                (
                    "sub_heading",
                    models.TextField(
                        blank=True, default="", verbose_name="Sub heading"
                    ),
                ),
                (
                    "mailchimp_id",
                    models.TextField(
                        blank=True, default="", verbose_name="Mailchimp ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup form",
            },
        ),
    ]
